const  SA=  {
    "country": "Saudi Arabia",
    "cities": [
      "Abha",
      "Abqaiq",
      "Al Bahah",
      "Al Faruq",
      "Al Hufuf",
      "Al Qatif",
      "Al Yamamah",
      "At Tuwal",
      "Buraidah",
      "Dammam",
      "Dhahran",
      "Hayil",
      "Jazirah",
      "Jazirah",
      "Jeddah",
      "Jizan",
      "Jubail",
      "Khamis Mushait",
      "Khobar",
      "Khulays",
      "Linah",
      "Madinat Yanbu as Sinaiyah",
      "Mecca",
      "Medina",
      "Mina",
      "Najran",
      "Rabigh",
      "Rahimah",
      "Rahman",
      "Ramdah",
      "Ras Tanura",
      "Riyadh",
      "Sabya",
      "Safwa",
      "Sakaka",
      "Sambah",
      "Sayhat",
      "Tabuk",
      "Yanbu` al Bahr"
    ]
  }
  export default SA;
